# Generated by Django 3.1.5 on 2021-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210415_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='thumbnail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
