# Generated by Django 3.1.5 on 2021-04-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210420_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
